title: Byte
description: Deep dives into core programming, system architecture, and modern DevOps.
url: "https://byte.sojwal.dev"
permalink: /:title/
future: true
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
